test(fixtures): Support shared mock requests
https://requests-mock.readthedocs.io/en/latest/fixture.html#fixtures

Unfortunately, the Pytest `--pdb` option disables `TestCase.tearDown` to preserve test
state in the debugging session.  This clashes with a check in `fixtures` that
sub-classes are properly formed and calling all MRO `tearDown()` methods:

    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    'NoneType' object is not iterable

    During handling of the above exception, another exception occurred:
    NOTE: Incompatible Exception Representation, displaying natively:

    testtools.testresult.real._StringException: traceback-1: {{{
    ValueError: In File: /home/rpatterson/src/media/feed-archiver/src/feedarchiver/tests/test_feed.py
    TestCase.tearDown was not called. Have you upcalled all the way up the hierarchy from your tearDown? e.g. Call super(FeedarchiverTests, self).tearDown() from your tearDown().
    }}}

Will have to revert this and find another way to share request mocks in the next commit.